spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**, /user/**, /api/user/**, /api/admin/**, /api/roles/**, /api/permissions/**
        - id: BUDGET-SERVICE
          uri: ${BUDGET_SERVICE_URL}
          predicates:
            - Path= /api/budgets/**
        - id: CHAT-SERVICE
          uri: ${CHAT_SERVICE_URL}
          predicates:
            - Path= /api/chats/**
        - id: FRIENDSHIP-SERVICE
          uri: ${FRIENDSHIP_SERVICE_URL}
          predicates:
            - Path= /api/friendships/**,/api/groups/**
        - id: PAYMENT-SERVICE
          uri: ${PAYMENT_SERVICE_URL}
          predicates:
            - Path= /api/payment-methods/**
        - id: CATEGORY-SERVICE
          uri: ${CATEGORY_SERVICE_URL}
          predicates:
            - Path= /api/categories/**
        - id: BILL-SERVICE
          uri: ${BILL_SERVICE_URL}
          predicates:
            - Path= /api/bills/**
        - id: AUDIT-SERVICE
          uri: ${AUDIT_SERVICE_URL}
          predicates:
            - Path=/api/audit-logs/**, /audit-logs/**
        - id: EXPENSE-TRACKING-SYSTEM
          uri: ${EXPENSE_TRACKING_SERVICE_URL}
          predicates:
            - Path= /api/expenses/**, /api/settings/**, /api/budgets/**, /api/bills/** , /api/categories/**,/daily-summary/**, /api/friendships/**, /api/investment/**,/api/payment-methods/**
        - id: NOTIFICATION-SERVICE
          uri: ${NOTIFICATION_SERVICE_URL}
          predicates:
            - Path=/api/notifications/**, /notifications/** , /api/notification-preferences/**
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: "Access-Control-Allow-Origin"
            strategy: "RETAIN_FIRST"
        - name: DedupeResponseHeader
          args:
            name: "Access-Control-Allow-Credentials"
            strategy: "RETAIN_FIRST"
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  datasource:
    url: jdbc:mysql://mysql:3306/gateway_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval: 5s
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
