server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG # For Gateway specific logs
    org.springframework.cloud.openfeign: DEBUG # For Feign client logs

spring:
  application:
    name: GATEWAY-SERVICE
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: USER-SERVICE
          uri: ${USER_SERVICE_URL:http://localhost:6001}
          predicates:
            - Path=/auth/**, /user/**, /api/user/**, /api/admin/**, /api/roles/**, /api/permissions/**
        - id: ANALYTICS-SERVICE
          uri: ${ANALYTICS_SERVICE_URL:http://localhost:7004}
          predicates:
            - Path= /api/analytics/**
        - id: BUDGET-SERVICE
          uri: ${BUDGET_SERVICE_URL:http://localhost:6005}
          predicates:
            - Path= /api/budgets/**
        - id: CHAT-SERVICE
          uri: ${CHAT_SERVICE_URL:http://localhost:7001}
          predicates:
            - Path= /api/chats/**
        - id: FRIENDSHIP-SERVICE
          uri: ${FRIENDSHIP_SERVICE_URL:http://localhost:6009}
          predicates:
            - Path= /api/friendships/**,/api/groups/**, /api/activities/**
        - id: PAYMENT-SERVICE
          uri: ${PAYMENT_SERVICE_URL:http://localhost:6006}
          predicates:
            - Path= /api/payment-methods/**
        - id: CATEGORY-SERVICE
          uri: ${CATEGORY_SERVICE_URL:http://localhost:6008}
          predicates:
            - Path= /api/categories/**
        - id: BILL-SERVICE
          uri: ${BILL_SERVICE_URL:http://localhost:6007}
          predicates:
            - Path= /api/bills/**
        - id: AUDIT-SERVICE
          uri: ${AUDIT_SERVICE_URL:http://localhost:6004}
          predicates:
            - Path=/api/audit-logs/**, /audit-logs/**
        - id: EXPENSE-TRACKING-SYSTEM
          uri: ${EXPENSE_TRACKING_SERVICE_URL:http://localhost:6000}
          predicates:
            - Path= /api/expenses/**, /api/settings/**, /api/budgets/**, /api/bills/** , /api/categories/**,/daily-summary/**, /api/friendships/**, /api/investment/**,/api/payment-methods/**,/api/bulk/**
        - id: NOTIFICATION-SERVICE
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:6003}
          predicates:
            - Path=/api/notifications/**, /notifications/** , /api/notification-preferences/**
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: "Access-Control-Allow-Origin"
            strategy: "RETAIN_FIRST" # Choose "RETAIN_FIRST", "RETAIN_LAST", or "RETAIN_UNIQUE"
        - name: DedupeResponseHeader
          args:
            name: "Access-Control-Allow-Credentials"
            strategy: "RETAIN_FIRST"
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  datasource:
    url: jdbc:mysql://localhost:5000/gateway_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval: 5s
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

gateway:
  rate-limit:
    enabled: true
    requests: 10
    window-seconds: 60
